[package]

name = "emailaddress"
version = "0.3.1"
authors = ["Paul Woolcock <paul@woolcock.us>"]
description = "Simple email address type and parser"
repository = "https://github.com/pwoolcoc/emailaddress-rs"
keywords = ["email"]
license = "MIT"
